name: 部署到GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 部署目标子文件夹
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./25215250232陈钧荣
          force_orphan: true # 强制gh-pages分支为独立分支，避免历史文件干扰
